/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_f;

/**
 *
 * @author MaHmOUd
 */
public class StartFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bu_Admin = new javax.swing.JButton();
        bu_coach = new javax.swing.JButton();
        bu_customer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bu_Admin.setForeground(new java.awt.Color(255, 255, 255));
        bu_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/admin-with-cogwheels.png"))); // NOI18N
        bu_Admin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bu_Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bu_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_AdminActionPerformed(evt);
            }
        });
        getContentPane().add(bu_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 118, 130, 130));

        bu_coach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/exercise (1).png"))); // NOI18N
        bu_coach.setBorder(null);
        bu_coach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bu_coach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_coachActionPerformed(evt);
            }
        });
        getContentPane().add(bu_coach, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 128, 128));

        bu_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/customer.png"))); // NOI18N
        bu_customer.setBorder(null);
        bu_customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bu_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_customerActionPerformed(evt);
            }
        });
        getContentPane().add(bu_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 128, 128));
        bu_customer.getAccessibleContext().setAccessibleName("Customer");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/start-01.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bu_coachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_coachActionPerformed
          setVisible(false);       
          new coach().setVisible(true);
    }//GEN-LAST:event_bu_coachActionPerformed

    private void bu_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_customerActionPerformed
         setVisible(false);       
          new customer().setVisible(true);
    }//GEN-LAST:event_bu_customerActionPerformed

    private void bu_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_AdminActionPerformed
        setVisible(false);
        new NewJFrame().setVisible(true);
    }//GEN-LAST:event_bu_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bu_Admin;
    private javax.swing.JButton bu_coach;
    private javax.swing.JButton bu_customer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
